### ISSUE TITLE
Questionable label beating a dead horse

### ISSUE THREAD

**Issue by cameodemon** [kellyelton/OCTGN#1346]
everything is questionable, this label is meaningless and at worst passive aggressive

**Comment by brine** [comment]
don't abuse the issue tracker please.

**Comment by kellyelton** [comment]
WAAT?!?!?

**Comment by kellyelton** [comment]
Lets be real, the way we decide to use labels for our workflow isn't even relevant to you and it also isn't even valid for you to scrutinize it.

**Comment by kellyelton** [comment]
Also, only the actual questionable stuff on github is marked questionable...with 200 open tickets, only 16 are marked questionable, don't be dramatic.
