### ISSUE TITLE
Feature Request (or question, if this already exists): detecting which cards are selected

### ISSUE THREAD

**Issue by anandaguneratne** [kellyelton/OCTGN#1348]
I have some code that triggers on moving a card using onMoveCard(). It works fine when only one card is moved, but does not behave as intended if multiple cards are selected (such as by dragging a box around different cards). I have looked everywhere to try to find a function that will return a list of the current cards that are selected, but can't find anything. So:

1. If this already exists, please let me know how I can retrieve this information
2. If this does not exist, please implement this feature.

Thanks!

**Comment by brine** [comment]
related to https://github.com/kellyelton/OCTGN/issues/1217

**Comment by kellyelton** [comment]
Yeah this seems like it would be a bug.

**Comment by brine** [comment]
in terms of 'fixing' this properly, one of two things would need to happen:
1) the onMoveCard event passes a list of card objects as the selection, even if there's just one card
2) onMoveCard needs to trigger independently for each card in the selection

**Comment by kellyelton** [comment]
I would prefer the first option I think...Or maybe make a new event OnMoveCards and depreciate the previous one.

**Comment by kellyelton** [comment]
Actually a big problem with this is that every card move gets networked and called and handled individually...so we'd also have to add a new networking call to make this work...

**Comment by kellyelton** [comment]
Ok, so depending on what api version you use, the event will be different

If you're using 3.1.0.0 you can attach to `OnMoveCards(player,cards[], fromGroup[], toGroup[], oldIndexes[], indexes[], oldx[], oldy[], x[], y[], highlights[], markers[])`

If you're using 3.1.0.1 and the event was NOT invoked from from a script, you can use `OnMoveCards(player,cards[], fromGroup[], toGroup[], oldIndexes[], indexes[], oldx[], oldy[], x[], y[], highlights[], markers[])`

If it WAS invoked from a script, you can use `OnScriptedMoveCards(player,cards[], fromGroup[], toGroup[], oldIndexes[], indexes[], oldx[], oldy[], x[], y[], highlights[], markers[])`

**Comment by kellyelton** [comment]
Due to the fact that the old version is kind of dirty, we will be removing it from OCTGN at 7/27/2015 .
