### ISSUE TITLE
Add ability to anchor card to table top so it is unmovable

### ISSUE THREAD

**Issue by sIKE23** [kellyelton/OCTGN#1349]
- User (Card Controller) should be able to anchor/unanchor card
- Should be scriptable via Python
- Small Lock icon in a top corner to indicate that the card has been anchored

**Comment by kellyelton** [comment]
Just need to add a visual lock or something on the card if it's anchored(or probably an anchor icon), and then just test it and it's done.

card.anchored returns if it's anchored or not
card.setAnchored(cardId, anchored) sets the card being anchored or not

using python, you can only anchor cards on the table(in theory)

**Comment by brine** [comment]
setAnchor, why u ed'ing it

**Comment by kellyelton** [comment]
R u fucking with me?

**Comment by sIKE23** [comment]
In what branch is this work in?

**Comment by kellyelton** [comment]
Test

**Comment by brine** [comment]
the API names may change so don't get attached to them

**Comment by kellyelton** [comment]
That's true

**Comment by kellyelton** [comment]
think about it though brine...does it make sense for a card to be "Anchor" or "Anchored"???

**Comment by kellyelton** [comment]
Also, this is kind of cool...You could use this for all sorts of stuff, like player avatars etc.

**Comment by brine** [comment]
Yeah but API calls should be simple, not necessarily grammatically correct.  Plus past tense looks weird.

**Comment by kellyelton** [comment]
Well it is simple if you can say it in your head and it makes sense, I'm not sure why ur butt hurt about it.

card.targetedBy ....should that be card.targetBy???

**Comment by kellyelton** [comment]
Only change I could see justifying would be changing `anchored` to `isAnchored`

**Comment by sIKE23** [comment]
Potato/Tomato right?

**Comment by sIKE23** [comment]
That would match up with most of the other items in OCTGN....

//FC
