### ISSUE TITLE
Performing a table.create to create a card on the table during OnGameStart breaks the OnGameStart method

### ISSUE THREAD

**Issue by sIKE23** [kellyelton/OCTGN#1359]
I am doing a card = table.create("a6ce63f9-a3fb-4ab2-8d9f-7d4b0108d7fd", dieCardX, dieCardY) during OnGameStart. Once the card is created everything just stops and nothing else follows. 

The weird thing is that I was not experiencing this in dev mode (Octgn.exe -x) only when you run the exe without the -x switch.

**Comment by anandaguneratne** [comment]
This also occurs when calling table.create in the onTableLoad event, or as part of any function (or sub-function) that is called by onGameStart or onTableLoad.
