### ISSUE TITLE
New event when a player fetches information from a face-down card.

### ISSUE THREAD

**Issue by db0** [kellyelton/OCTGN#1366]
With the new change in OCTGN where card info is available always, it's easier than ever to cheat by inserting custom code in your local definition's scripts to whisper hidden info to you.

I'd like to request an event added to OCTGN which fires every time face-down card information is retrieved by a player. Then I could add a simple function which sends a whisper to everyone else saying something like "player has retrieved hidden info for card at player.Deck[1]" 

The API should simply send the card object being looked at.

**Comment by db0** [comment]
Added or won't fix?

**Comment by kellyelton** [comment]
Oh sorry, won't fix. I ment to leave a message. This wouldn't work the ways things are setup now.

**Comment by db0** [comment]
Oh? Can you elaborate? What's to stop me from doing ```whisper("{}".format(players[1].deck[0].Name))``` ?

**Comment by brine** [comment]
nothing was stopping you previously from doing

```python
mute()
hiddenCard = players[1].Deck[1]
hiddenCard.isFaceUp = True
whisper("{}".format(hiddenCard.Name))
hiddenCard.isFaceUp = False
```

which is effectively the same thing with just as few warnings to the other player

**Comment by brine** [comment]
the ability to hack a game def locally for cheating purposes has always been there, nothing will change until the game log gets fixed and/or the scripting gets pushed server-side

**Comment by db0** [comment]
I know. I just think this might be an easy intermediate solution.

**Comment by kellyelton** [comment]
Well until the scripting is server side, it doesn't really matter.
