### ISSUE TITLE
onMoveCards fromGroup and toGroup are reversed

### ISSUE THREAD

**Issue by db0** [kellyelton/OCTGN#1376]
When moving a single card from hand tot table, fromGroup[0] is table and toGroup[0] is hand.

**Comment by db0** [comment]
Actually, this is not exactly correct. Something weird is going on

If I write the following

```
def checkMovedCards(player,cards,fromGroups,toGroups,oldIndex,index,oldX,oldY,x,y,isScriptMove,highlight = None,markers = None):
   for iter in range(len(cards)):
      card = cards[iter]
      toGroup = toGroups[iter]
      fromGroup = fromGroups[iter]
      if fromGroup == me.hand: confirm('Hand!')
      notify("card = {}, fromGroup = {}. toGroup = {}".format(card.Name,toGroup.name,fromGroup.name)) #Debug
```
If I run the above with a drag&drop from hand to table, the notifyu will say the fromGroup is the Table and the toGroup is  the hand, but the IF conditional will be true. o.)

**Comment by kellyelton** [comment]
your notify is backwards

**Comment by kellyelton** [comment]
Should be 
    notify("card = {}, fromGroup = {}. toGroup = {}".format(card.Name,fromGroup.name,toGroup.name)) #Debug
instead of 
    notify("card = {}, fromGroup = {}. toGroup = {}".format(card.Name,toGroup.name,fromGroup.name)) #Debug

**Comment by db0** [comment]
/facepalm

I'll try it again and let you know. It was not behaving as expected so I thought this was the reason, but it must be something else.

**Comment by kellyelton** [comment]
Yeah just let me know, pretty easy mistake to make.
