### ISSUE TITLE
Facedown: Portrait, Faceup: Landscape?

### ISSUE THREAD

**Issue by GeckoTH** [kellyelton/OCTGN#1391]
I have a deck of cards that all use the same cardback image. Most of these cards are portrait, or vertically oriented cards, and some of them are landscape cards. I've used the new CardSize feature to define the dimensions of the landscape cards.

When dealing these cards facedown to the table, the landscape cards show a stretched cardback image to fit the short and wide CardSize dimensions. Is it possible to have these landscape cards look identical to the portrait cards when facedown, yet reveal themselves as landscape cards when flipped faceup?

**Comment by brine** [comment]
for reference, the plan we discussed a while back was to include backWidth, backHeight, and backRadius values within each ``<cardSize>`` tag

**Comment by sIKE23** [comment]
This is the same as #1389....

**Comment by brine** [comment]
i had a feeling we already had this...
