### ISSUE TITLE
A way to define tailor-made actions, specific to some cards or card properties.

### ISSUE THREAD

**Issue by db0** [kellyelton/OCTGN#144]
Possibly something for the far future, but I'd like the ability to define in my game card actions that will only appear *only* when a specific card, or card with a specific property (such as card.type) is right-clicked.

This would allow game designers to implement complex and very specific actions for each card if they so wished, without cluttering the context menus.

**Comment by kellyelton** [comment]
Doesn't this exist now with that sutff that one guy made? Makes certain menu items visible based on some arbitrary python code? #1304
