### ISSUE TITLE
Custom UI that's game-specific

### ISSUE THREAD

**Issue by unrealed** [kellyelton/OCTGN#992]
I'm not a creator, but it seems like it'd be useful for games to be able to have custom bits of UI. 

I've seen a couple games that have markers and tokens that have multiple sides to denote the phases of the game and it seems like custom UIs would help solve those problems.

**Comment by kellyelton** [comment]
I'm not sure if this completely covers what you're taking about #105

You only describe phase management, which that is about. If you want to make this ticket about some other form of custom UI we can re open it and go from there.
